baseURL = 'https://videos.pornstar.monster/'
languageCode = 'en-us'
title = 'Free Porn Videos'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = 'lightbi-hugo'


googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[permalinks]
  posts = '/:slug/'
  tags = '/:slug/'
  
  
[minify]
  minifyOutput = false
  

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  taxonomyTerm = ["HTML"]

  
[params]
    enableRSS = true
    showRelatedPosts = true #for lightbi related posts
    description = "Pornstar Monster"
    author = "Pornstar Monster"
    selfHosted = true
	mainSections = ["post","posts"]
	#dateFormat = "2 January 2023"
	comments = false
	#readingTime = true
	#wordCount = true
	useHLJS = false
	socialShare = true
	delayDisqus = true
	summaryLength  = "9"
	gcse = false
	Lastmod = true
	rss = false 
	pagination = "10"
	hideAuthor = true
	darkMode = false
    showTranslations = false #i created this var in config to hide translated pages links under thumbnails

  [params.mytags]
	go = 'Go is developed by google.'
	php = 'PHP is the most populer language for web developemnt.'



[languages]
  [languages.en]
  languageName = "English"
  weight = 1
  title = "Pornstars Porn Videos"

[languages.bn]
  languageName = "বাংলা"
  weight = 2
  title = "বাংলা পর্ণ ভিডিও"

[languages.hi]
  languageName = "हिन्दी"
  weight = 3
  title = "अश्लील वीडियो"

[languages.es]
  languageName = "Español"
  weight = 4
  title = "Vídeos pornografía gratis"

[languages.ru]
  languageName = "Русский"
  weight = 5
  title = "русское порно"

[languages.de]
  languageName = "Deutsch"
  weight = 6
  title = "gratis porno deutsch"

[languages.fr]
  languageName = "Français"
  weight = 7
  title = "vidéo porno français"

[languages.ja]
  languageName = "日本語"
  weight = 8
  title = "ポルノ 動画"

[languages.pt]
  languageName = "Português"
  weight = 9
  title = "Videos porno grátis"

[languages.tr]
  languageName = "Türkçe"
  weight = 10
  title = "türk porno HD"

[languages.it]
  languageName = "Italiano"
  weight = 11
  title = "video porno italiano gratis"

[languages.fa]
  languageName = "فارسی"
  languageDirection = "rtl"
  weight = 12
  title = "پورن"

[languages.nl]
  languageName = "Nederlands"
  weight = 13
  title = "gratis nederlandse porno"

[languages.pl]
  languageName = "Polski"
  weight = 14
  title = "polish porn videos"

[languages.zh]
  languageName = "中文"
  weight = 15
  title = "免费色情影片"

[languages.vi]
  languageName = "Tiếng Việt"
  weight = 16
  title = "khiêu dâm porn"

[languages.id]
  languageName = "Bahasa Indonesia"
  weight = 17
  title = "vidio porno"

[languages.cs]
  languageName = "Čeština"
  weight = 18
  title = "Czech porn"

[languages.ko]
  languageName = "한국어"
  weight = 19
  title = "포르노"

[languages.uk]
  languageName = "Українська"
  weight = 20
  title = "порно hd"

[languages.ar]
  languageName = "العربية"
  languageDirection = "rtl"
  weight = 21
  title = "افلام اباحيه"

[languages.el]
  languageName = "Ελληνικά"
  weight = 22
  title = "δωρεάν πορνό βίντεο"

[languages.iw]
  languageName = "עברית"
  languageDirection = "rtl"
  weight = 23
  title = "סרטי פורנו"

[languages.sv]
  languageName = "Svenska"
  weight = 24
  title = "gratis porr"

[languages.ro]
  languageName = "Română"
  weight = 25
  title = "filme porno"

[languages.hu]
  languageName = "Magyar"
  weight = 26
  title = "pornó filmek"

[languages.th]
  languageName = "ไทย"
  weight = 27
  title = "สื่อลามก วิดีโอ"

[languages.da]
  languageName = "Dansk"
  weight = 28
  title = "gratis porno"

[languages.sk]
  languageName = "Slovenčina"
  weight = 29
  title = "porno filmi"

[languages.fi]
  languageName = "Suomi"
  weight = 30
  title = "Free porno videot Finnish"

[languages.sr]
  languageName = "Српски"
  weight = 31
  title = "порно сек"

[languages.no]
  languageName = "Norsk"
  weight = 32
  title = "gratis pornovideoer"

[languages.bg]
  languageName = "Български"
  weight = 33
  title = "безплатни порно клипове"

[languages.lt]
  languageName = "Lietuvių"
  weight = 34
  title = "nemokami porno video"

[languages.sl]
  languageName = "Slovenščina"
  weight = 35
  title = "brezplačni porno videi"

[languages.ca]
  languageName = "Català"
  weight = 36
  title = "puto vídeo porno"

[languages.et]
  languageName = "Eesti"
  weight = 37
  title = "kuradi pornovideo"

[languages.lv]
  languageName = "Latviešu"
  weight = 38
  title = "sasodīti porno video"

[languages.hr]
  languageName = "Hrvatski"
  weight = 39
  title = "jebeni porno video"

[languages.as]
  languageName = "অসমীয়া"
  weight = 40
  title = "ভিডিও পৰ্ণ চুদাচুদি "

[languages.gu]
  languageName = "ગુજરાતી"
  weight = 41
  title = "અશ્લીલ વિડિઓ"

[languages.ml]
  languageName = "മലയാളം"
  weight = 42
  title = "അശ്ലീല വീഡിയോ"

[languages.ne]
  languageName = "नेपाली"
  weight = 43
  title = "अश्लील भिडियो"

[languages.mr]
  languageName = "मराठी"
  weight = 44
  title = "अश्लील व्हिडिओ"

[languages.pa]
  languageName = "ਪੰਜਾਬੀ"
  weight = 45
  title = "ਸੈਕਸ ਵੀਡੀਓ ਪੋਰਨ"

[languages.ta]
  languageName = "தமிழ்"
  weight = 46
  title = "ஆபாச வீடியோ"

[languages.ka]
  languageName = "ქართული"
  weight = 47
  title = "ಫಕಿಂಗ್ ಪೋರ್ನ್ ವಿಡಿಯೋ"

[languages.te]
  languageName = "తెలుగు"
  weight = 48
  title = "ఫకింగ్ పోర్న్ వీడియో"


[languages.or]
  languageName = "ଓଡ଼ିଆ"
  weight = 49
  title = "ସେକ୍ସି ପର୍ଣ୍ଣ ଭିଡିଓ |"

[languages.ur]
  languageName = "اردو"
  weight = 50
  title = "سیکسی فحش ویڈیو"

[languages.ms]
  languageName = "Bahasa Melayu"
  weight = 51
  title = "video lucah sialan"
   


#nav main menu

[[menu.main]]
    name = "Porn Stars"
    url = "https://www.pornstar.monster/"
    weight = 1	






#menu for footer

 #[[menu.footer]]
    #name = "हिन्दी"
    #url = "/hindi/"
    #weight = 1

  

