baseURL = 'https://videos.pornstar.monster/'
languageCode = 'en-us'
title = 'Free Porn Videos'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = 'lightbi-hugo'


googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[permalinks]
  posts = '/:slug/'
  tags = '/:slug/'
  
  
[minify]
  minifyOutput = false
  
[params]
    showRelatedPosts = true #for lightbi related posts
    description = "Pornstar Monster"
    author = "Pornstar Monster"
    selfHosted = true
	mainSections = ["post","posts"]
	#dateFormat = "2 January 2023"
	comments = false
	#readingTime = true
	#wordCount = true
	useHLJS = false
	socialShare = true
	delayDisqus = true
	summaryLength  = "9"
	gcse = false
	Lastmod = true
	rss = true 
	pagination = "10"
	hideAuthor = true
	darkMode = false
    showTranslations = false #i created this var in config to hide translated pages links under thumbnails

  [params.mytags]
	go = 'Go is developed by google.'
	php = 'PHP is the most populer language for web developemnt.'



[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Your Site Title in English"    
    #baseURL = 'https://videos.pornstar.monster/'

  [languages.bn]
    languageName = "Bengali"
    weight = 2
    title = "Your Site Title in Bengali"
    
    #baseURL = 'https://videos.pornstar.monster/bangla'


  [languages.hi]
    languageName = "Hindi"
    weight = 3
    title = "Your Site Title in Hindi"    
    #baseURL = 'https://videos.pornstar.monster/hindi'

#nav main menu

[[menu.main]]
    name = "Porn Stars"
    url = "https://www.pornstar.monster/"
    weight = 1	






#menu for footer

 #[[menu.footer]]
    #name = "हिन्दी"
    #url = "/hindi/"
    #weight = 1

  

